### ISSUE TITLE
Error send push notification

### ISSUE THREAD

**Issue by Macario** [hamidmedgjonaj/LaravelPushNotification#1]
Why this occurs?

ErrorException: stream_set_blocking() expects parameter 1 to be resource, boolean given in .../meddev/laravel-push-notification/src/Services/APNs/ApnService.php:153

**Comment by hamidmedgjonaj** [comment]
Can you check what are you getting fromt this config param: $url = Config::get('pushnotification.aps.server'); -> line 136

And also if you are using the development certificate than change the "server"  	=> "ssl://gateway.push.apple.com:2195", to "server"  	=> "ssl://gateway.sandbox.push.apple.com:2195",

**Comment by Macario** [comment]
This is my $url = ssl://gateway.push.apple.com:2195

So, I have to change to ssl://gateway.sandbox.push.apple.com:2195, right?

**Comment by Macario** [comment]
These are the params of stream_set_blocking(false, 0)

**Comment by Macario** [comment]
I don't want sending push notification to Apple. Is there possible to send only to Android using FCM? What's the configuration?

**Comment by Macario** [comment]
Hi. I solved my problem, thanks.
